### ISSUE TITLE
Package naming convention

### ISSUE THREAD

**Issue by IanTheEngineer** [ros-agriculture/microtractor#1]
@droter, I'm not 100% sure you intend to make this a ROS package, but if so, you'll likely want to convert the dash in `micro-tractor` to an underscore, `micro_tractor`, or the all-one-word, `microtractor`, to conform to package naming conventions:

http://www.ros.org/reps/rep-0144.html#package-naming

**Comment by droter** [comment]
Thanks for catching that Ian.  Fixed now.
